name: story_way
description: Instagram story like app for Codeway Task

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^3.0.1
  loading_animation_widget: ^1.2.0+4
  equatable: ^2.0.5
  hive: ^2.2.3
  shared_preferences: ^2.0.17
  sqflite: ^2.2.3
  hive_flutter: ^1.1.0
  video_player: ^2.5.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  assets:
    - ./assets/app_data.json
    - ./assets/story_1.mp4
    - ./assets/story_2.mp4
    - ./assets/story_3.mp4
    - ./assets/story_4.mp4
    - ./assets/story_5.mp4
    - ./assets/story_6.mp4
    - ./assets/story_7.mp4
    - ./assets/story_8.mp4

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
